export const GET_HOT_WORDS = 'GET_HOT_WORDS'                  // 获取热词
export const GET_GOODS_LIST = 'GET_GOODS_LIST'                // 获取商品列表
export const GET_GOODS_LIST_S = 'GET_GOODS_LIST_S'                // 获取商品列表 滚动时
export const GET_GOODS_DETAIL = 'GET_GOODS_DETAIL'             // 获取商品详情
export const GET_HOT_GOODS = 'GET_HOT_GOODS'                // 获取热门商品
export const GET_MALLS = 'GET_MALLS'                       // 获取商城列表
export const GET_CATEGORYS = 'GET_CATEGORYS'                // 获取商品类别
export const GET_GOODS_NOTIFY = 'GET_GOODS_NOTIFY'           // 获取新增商品的条目数
export const GET_THUMBS_ADD = 'GET_THUMBS_ADD'              // 增加点赞数
export const GET_THUMBS_ADD_DETAIL = 'GET_THUMBS_ADD_DETAIL'         // 增加点赞数 详情页
export const CHANGE_CONTACT_US_FLAG = 'CHANGE_CONTACT_US_FLAG'  // 更改contactUsFLag 的值
export const GET_MAYBE_LIKE = 'GET_MAYBE_LIKE'        // 获取猜你喜欢
export const GET_MALL_HOT = 'GET_MALL_HOT'           // 获取商城热门
export const GET_MAX_ID_SYNC = 'GET_MAX_ID_SYNC'           // 获取商品 最高 id 和 时间
export const GET_COUPONS = 'GET_COUPONS'           // 今日优惠券
export const GET_GIFTS_FOR_ALL = 'GET_GIFTS_FOR_ALL' // 获取gifts for all
export const GET_GIFTS_FOR_HER = 'GET_GIFTS_FOR_HER' // 获取gifts for her
export const GET_GIFTS_FOR_HIM = 'GET_GIFTS_FOR_HIM' // 获取gifts for him
export const GET_GIFTS_FOR_KIDS = 'GET_GIFTS_FOR_KIDS' // 获取gifts for kids
export const GET_GIFTS_FOR_SENIOR = 'GET_GIFTS_FOR_SENIOR' // 获取gifts for senior
